### ISSUE TITLE
Project doesn't compile in XCode 3.2.5

### ISSUE THREAD

**Issue by cullepm3** [gimenete/iOS-boilerplate#2]
/Users/cullepm3/Desktop/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:28:0 /Users/cullepm3/Desktop/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:28: error: 'backView' undeclared (first use in this function)

/Users/cullepm3/Desktop/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:92:0 /Users/cullepm3/Desktop/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:92: error: 'contentView' undeclared (first use in this function)

**Comment by AquaGeek** [comment]
What version of the iOS SDK are you using?

**Comment by cullepm3** [comment]
4.2

**Comment by MdBee** [comment]
Adding "NSDictionary\* info;" to SwipeableCell.h like this solved the problem for me:

@interface SwipeableCell : FastCell {

```
BOOL swipe;

NSDictionary* info;
```

}

**Comment by gimenete** [comment]
It happened when compiling for iOS device and not for the simulator. It is fixed now. Thank you!
